checkpoint:
  keep_interval_updates: 5
  no_epoch_checkpoints: true
  save_interval_updates: 10000
common:
  fp16: true
  log_format: simple
  log_interval: 200
  seed: 1337
  tensorboard_logdir: tblog
criterion:
  _name: hubert
  loss_weights:
  - 10
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
dataset:
  max_tokens: 1400000
  num_workers: 4
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  validate_interval_updates: 10000
  
distributed_training:
  ddp_backend: no_c10d
  distributed_backend: nccl
  distributed_world_size: 1
  find_unused_parameters: true
  nprocs_per_node: 5
hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
        - run
        - task.data
        - task.label_dir
        item_sep: __
        kv_sep: '-'
  run:
    dir: /tmp2/willymen
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 20000
model:
  _name: hubert
  activation_dropout: 0.0
  attention_dropout: 0.1
  conv_feature_layers: '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2'
  dropout: 0.1
  dropout_features: 0.1
  dropout_input: 0.1
  encoder_layerdrop: 0.05
  encoder_layers: 2
  extractor_mode: default
  feature_grad_mult: 0.1
  final_dim: 256
  label_rate: 100
  mask_prob: 0.8
  skip_masked: false
  skip_nomask: false
  untie_final_proj: true
optimization:
  clip_norm: 10.0
  lr:
  - 0.0005
  max_update: 250000
  update_freq:
  - 4
optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01
task:
  _name: hubert_pretraining
  data: /ntu-jason/preprocessing-360/tsv
  label_dir: /ntu-jason/preprocessing-360/phase1_labels
  label_rate: ${model.label_rate}
  labels: '["km"]'
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false
  pad_audio: false
  random_crop: true
  sample_rate: 16000
